FROM bitnami/spark:latest
USER root
# Utilidades de consola: clear (ncurses), editores, red, etc.
RUN apt-get update && apt-get install -y --no-install-recommends \
    ncurses-bin nano vim-tiny less curl wget git iputils-ping procps ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# --- LOGS SILENCIOSOS ---
# Copiamos log4j2.properties y spark-defaults.conf a la carpeta de conf de Spark
COPY log4j2.properties /opt/bitnami/spark/conf/log4j2.properties
COPY spark-defaults.conf /opt/bitnami/spark/conf/spark-defaults.conf

# Forzamos que Spark use nuestro log4j2.properties (clave para eliminar "Setting default log level to WARN")
ENV SPARK_SUBMIT_OPTS="-Dlog4j.configurationFile=/opt/bitnami/spark/conf/log4j2.properties"

WORKDIR /workspace